#!/bin/sh
# Run a cart on the console.
#
#   ./run                     boot the default cart
#   ./run --cart hello         boot a specific cart
#   ./run --list               list available carts
#   ./run --hud                start with the debug overlay on
#
cd "$(dirname "$0")"
DIR=$(pwd)
DRAGONRUBY=$(dirname "$DIR")/dragonruby
exec "$DRAGONRUBY" "$DIR" "$@"
